const DEFAULT_TIMEOUT_MS = Number(process.env.API_TIMEOUT_MS || 15000);
const SLOW_API_THRESHOLD_MS = Number(process.env.SLOW_API_THRESHOLD_MS || 1000);
const AUTO_TEST_INTERVAL_SECONDS = Number(process.env.AUTO_TEST_INTERVAL_SECONDS || 0);

module.exports = {
  DEFAULT_TIMEOUT_MS,
  SLOW_API_THRESHOLD_MS,
  AUTO_TEST_INTERVAL_SECONDS,
};
